### ISSUE TITLE
#1 Identificar las clases del sistema, atributos y métodos

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#1]
Basándose en los requerimientos funcionales del proyecto ARGBroker Demo, se solicita:

- Identificar las clases del sistema, atributos y métodos.

**Comment by marceloportillodev** [comment]
Falta pulir

![ProyectoFinal](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/1327770/4b79fe1f-d3c2-4e56-ab6a-aebad337c328)

**Comment by marceloportillodev** [comment]
Actualizo las clases

![ProyectoFinal-clases](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/1327770/5613e312-8d1e-4271-ae30-b32f00cec846)

**Comment by marceloportillodev** [comment]
Inversor
---------------------------------
- id_tipo_documento
- cuit
- nro_documento
- nombre
- apellido
- Tipodocumento_id_tipo_documento
- Portfolio_id_portafolio
- User_user
- Tipoinversor_id_tipo_inversor
---------------------------------
crear_inversor()
modificar_inversor()


TipoInversor
--------------------------
- id_tipo_inversor
- nombre
--------------------------
editar_nombre()

TipoDocumento
--------------------------
- id_tipo_documento
- nombre
-------------------------- 
editar_nombre()


Transaccion
--------------------------
- id_transaccion
- fecha_hora
- cantidad_acciones
- precio
- comision_broker
- transaccioncol
- Accion_id_accion
- Inversor_cuit
- Tipotransaccion_id_Tipo_transaccion 
--------------------------
crear_transaccion()



TipoTransaccion
--------------------------
- id_tipo_transaccion
- nombre
--------------------------
editar_nombre()


User
--------------------------
- user
- contrasena
- perfil_id_perfil
--------------------------
crear_usuario()
login()
logout()
recuperar_contrasena()


Perfil
--------------------------
- id_perfil
- nombre
- permiso_id_permiso
--------------------------
editar_nombre()


Permiso
--------------------------
- id_permiso
- nombre
--------------------------
editar_nombre()


Portafolio
-----------------------
- id_portafolio
- ganancia_total
- saldo_cuenta
- perdida_total
-----------------------
Calcular_total_ invertido()
Listar_cantidad_de_acciones _compradas()
Calcular_ganancia()
Calcular_perdida()



DetallePortafolio
--------------------------
- id_detalle_portafolio
- cantidad_acciones_compradas
- precio_por_accion
- monto_invertido
- perdida
- ganancia
- portafolio_id_portafolio
- accion_id_accion
--------------------------
calcular_ganancia()
calcular_perdida()
cargar_datos_de_accion()




Accion
--------------------------
- id_accion
- simbolo
- nombre
- cantidad_compra_diaria
- precio_venta_actual
- cantidad_venta_diaria
- apertura
- minimo_diario
- maximo_diario
- ultimo_cierre
- empresa_cuit
--------------------------
Listar acciones()

Empresa
--------------------------
- cuit
- nombre
- razon_social
- empresacol
--------------------------

**Comment by gusta37** [comment]
Ya se pasa al wiki
