### ISSUE TITLE
#5 Crear el modelo relacional resultante de la normalización

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#10]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Crear el modelo relacional resultante de la normalización, representando las entidades
  como tablas con sus respectivos atributos y relaciones. Definir las claves primarias y
  foráneas necesarias para establecer las relaciones entre las tablas.

**Comment by LucasJQ13** [comment]
a continuación se adjunta el modelo relacional resultante de la normalización, esta imagen fue subida en el punto 4 de programacion por Julio 
![336270259-598c5a40-b234-44d5-8632-f6dc282e7368](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/167819372/dd216689-a87a-4294-a38c-09146a578e02)
