### ISSUE TITLE
#6 Documentar el diseño de la base de datos

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#11]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Documentar el diseño de la base de datos, incluyendo una pequeña descripción de
  cada tabla. Y las aclaraciones que creas necesarias en cada una de ellas. Por
  ejemplo si se realizó una suposición de algo que no estaba en el enunciado y eso
  determinó que una relación es uno a muchos, cuando se podría haber interpretado
  por una ambigüedad que podía ser muchos a muchos, dejar asentada tal suposición.

**Comment by LucasJQ13** [comment]
Tabla: DetallePortafolio
•	Descripción: Detalla las acciones dentro del portafolio del inversor.
•	Atributos:
•	id_detalle_portafolio (PK): Clave primaria del detalle del portafolio.
•	cantidad_acciones_compradas: Cantidad de acciones compradas.
•	precio_por_accion: Precio de cada acción.
•	monto_invertido: Monto invertido en compra de acciones.
•	perdida: Perdida del capital por compra de las acciones.
•	ganancia: Ganancia por compra de las acciones.
•	Portafolio_id_portafolio (FK): Clave foranea al portafolio.
•	Accion_id_accion (FK): Clave foranea a la acción.

Tabla: Permiso
•	Descripción: Guarda los permisos que son asignados a los usuarios.
•	Atributos:
•	id_permiso (PK): Clave primaria del permiso.
•	nombre: Nombre del permiso
Tabla: TipoDocumento
•	Descripción: Guarda el tipo de documento del usuario.
•	Atributos:
•	id_tipo_documento (PK): Clave primaria del tipo de documento
•	nombre: Nombre del tipo de documento.
Tabla: Transaccion
•	Descripción: Registra las transacciones realizadas por los inversores.
•	Atributos:
•	id_transaccion (PK): Clave primaria de la transacción.
•	fecha_hora: Fecha y hora de la transacción.
•	cantidad_acciones: Cantidad de acciones compradas o vendidas en la transacción.
•	precio: Precio total de las acciones compradas o vendidas.
•	comision_broker: Comisión del broker.
•	Inversor_cuit (FK): Clave foránea del inversor.
•	Accion_id_accion (FK): Clave foránea de la accion.
•	id_Tipo_Transaccion (FK): Clave foránea de la transacción.
Tabla: Accion
•	Descripción: Almacena información sobre las acciones disponibles.
•	Atributos:
•	id_accion (PK): Clave primaria de la acción.
•	simbolo: Símbolo de la empresa de la acción.
•	nombre: Nombre de la empresa de la acción.
•	cantidad_compra_diaria: Cantidad de acciones compradas por día.
•	precio_venta_actual: Precio actual de venta por acción.
•	cantidad_venta_diaria: Cantidad de acciones vendidas por día.
•	apertura: Precio de apertura de la acción al inicio del día.
•	minimo_diario: Precio mínimo diario de la acción.
•	maximo_diario: Precio máximo diario de la acción.
•	ultimo_cierre: Precio de cierre de la acción al final del día.
•	Cuit_Empresa (FK): Clave foranea a la empresa de la acción.




Tabla: TipoTransaccion
•	Descripción: Contiene los diferentes tipos de transacciones posibles.
•	Atributos:
•	id_Tipo_Transaccion (PK): Identificador único del tipo de transacción.
•	nombre: Nombre descriptivo del tipo de transacción.

Tabla: Empresa
•	Descripción: Guarda los datos de las empresas que emiten las acciones.
•	Atributos:
•	cuit (PK): Clave primaria de la empresa.
•	nombre: Nombre de la empresa.
•	razon_social: Razón social de la empresa.

**Comment by LucasJQ13** [comment]
Relación Uno a Muchos (1:N):
Entre TipoInversor e Inversor asumimos una relación 1 a Muchos ya que un tipo de inversor puede aplicarse a muchos inversores, pero cada inversor solo puede tener ser un tipo de inversor.
También aplicamos esta lógica a las siguientes relaciones:
•	TipoDocumento e Inversor.
•	Inversor y Transacción
•	Acción y Transacción
•	TipoTransaccion y Transacción
•	Empresa y Acción
•	Portafolio y DetallePortafolio.
•	Acción y DetallePortafolio
•	Perfil y User
•	Permiso y Perfil
Relación Uno a Uno (1:1):
•	Entre Inversor y Portafolio se asumió una relación 1:1 ya que cada inversor tiene un único portafolio y viceversa. Esta relación se podría haber interpretado como uno a muchos (1:N) si se permitiera a un inversor tener múltiples portafolios, pero para mantener la simplicidad el equipo optó por 1:1.

Relación Mucho a Mucho (N:N):
•	DetallePortafolio: Se creó esta tabla para poder manejar la relación entre Portafolio y Acción, ya que un portafolio puede contener múltiples acciones y una acción puede estar en múltiples portafolios relación (N:N).
