### ISSUE TITLE
Matricula, legislación y registro

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#14]
· Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la
Profesión.
· Describir que requerimientos deben cumplir el código programado y las bases de
datos según la legislación vigente
· Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de
software.

**Comment by gusta37** [comment]
Se realiza en el wiki:

https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/wiki/04%E2%80%90-%C3%89tica-y-Deontolog%C3%ADa-Profesional#3-describir-qui%C3%A9nes-y-ante-quien-deben-matricularse-a-nivel-provincial-para-ejercer-la-profesi%C3%B3n

https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/wiki/04%E2%80%90-%C3%89tica-y-Deontolog%C3%ADa-Profesional#4--describir-que-requerimientos-deben-cumplir-el-c%C3%B3digo-programado-y-las-bases-de-datos-seg%C3%BAn-la-legislaci%C3%B3n-vigente

https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/wiki/04%E2%80%90-%C3%89tica-y-Deontolog%C3%ADa-Profesional#5--enumerar-los-pasos-para-que-argbroker-sea-parte-del-registro-nacional-de-software

**Comment by gusta37** [comment]
se realiza en el wiki
