### ISSUE TITLE
Medidas Legales, consecuencias ante Incumplimientos y malas prácticas en el Grupo de trabajo

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#15]
· Si un integrante del grupo no realiza el trámite de matriculación, que pena le corresponde a nivel provincial.
· Si el código es replicado, describir como la Ley de Propiedad Intelectual puede salvaguardar a ARGBroker.
· Si un integrante del grupo divulga los datos de la base de datos interna, describir como legalmente deberían accionar los demás.
· Si otro integrante del grupo reutiliza el código para fines personales, describir como legalmente deberían accionar los demás según la Legislación de la Provincia de Córdoba y el Código Penal Argentino.
· Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

**Comment by AlandMarini** [comment]
1. Si un integrante del grupo no realiza el trámite de matriculación, ¿qué pena le corresponde a nivel provincial?

Multas y Sanciones Administrativas: El integrante que no realice el trámite de matriculación puede ser sancionado con multas económicas y otras sanciones administrativas impuestas por el colegio profesional correspondiente.
Inhabilitación: En casos graves, puede ser inhabilitado para ejercer la profesión hasta regularizar su situación.

Referencias Legales:
Ley Provincial N° 9450: Regula el ejercicio de las profesiones en ingeniería y ramas afines en Córdoba, incluyendo la obligación de matriculación.

2. Si el código es replicado, ¿cómo puede la Ley de Propiedad Intelectual salvaguardar a ARGBroker?
La Ley de Propiedad Intelectual en Argentina protege los derechos de autor sobre las obras creativas, incluyendo el software.

Protección:
Derecho de Autor: ARGBroker puede registrar el software en la Dirección Nacional del Derecho de Autor (DNDA). Esto brinda una protección legal sólida contra la copia no autorizada.
Acciones Legales: Si se detecta la replicación del código, ARGBroker puede iniciar acciones legales contra los infractores por violación de derechos de autor.
Compensaciones: La ley permite reclamar daños y perjuicios por el uso no autorizado del software.

Referencias Legales:
Ley de Propiedad Intelectual (Ley N° 11.723): Establece los derechos de autor sobre obras literarias, científicas y artísticas, incluyendo el software.

3. Si un integrante del grupo divulga los datos de la base de datos interna, ¿cómo legalmente deberían accionar los demás?
La divulgación no autorizada de datos confidenciales es una violación grave que puede ser tratada tanto en términos civiles como penales.

Acciones Legales:
Denuncia Penal: Iniciar una denuncia penal por violación de la Ley de Protección de Datos Personales.
Acción Civil: Presentar una demanda civil por daños y perjuicios.

Referencias Legales:
Ley de Protección de Datos Personales (Ley N° 25.326): Establece sanciones para la divulgación no autorizada de datos personales.
Código Penal Argentino, Artículo 157 bis: Penaliza la divulgación indebida de datos personales.

4. Si otro integrante del grupo reutiliza el código para fines personales, ¿cómo legalmente deberían accionar los demás según la Legislación de la Provincia de Córdoba y el Código Penal Argentino?
El uso no autorizado del código desarrollado para la empresa para fines personales es una infracción que puede ser tratada legalmente.

Acciones Legales:
Demanda Civil: Presentar una demanda civil por violación de derechos de propiedad intelectual y reclamar daños y perjuicios.
Denuncia Penal: Iniciar una denuncia penal por violación de la Ley de Propiedad Intelectual.
Sanciones Disciplinarias: Implementar sanciones disciplinarias dentro de la empresa según el contrato de trabajo.

Referencias Legales:
Ley de Propiedad Intelectual (Ley N° 11.723): Protege los derechos de autor sobre el software.
Código Penal Argentino, Artículo 172: Penaliza la defraudación, que puede aplicarse al uso indebido del código.
Ley Provincial N° 9450: Regula el ejercicio profesional y las sanciones por infracciones éticas.

5. Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, ¿qué instrumento legal respalda a ARGBroker?
La protección internacional de los derechos de autor sobre el software puede ser gestionada mediante tratados y convenios internacionales.

Protección Internacional:
Convenio de Berna: Proporciona protección a las obras literarias y artísticas (incluyendo software) en todos los países miembros.
WIPO (World Intellectual Property Organization): La Organización Mundial de la Propiedad Intelectual puede ser un recurso para proteger y reclamar los derechos de propiedad intelectual a nivel internacional.
DMCA (Digital Millennium Copyright Act, USA): En Estados Unidos, se pueden realizar reclamos bajo esta ley para retirar contenido que infrinja derechos de autor en plataformas digitales.
Acciones Legales Internacionales: ARGBroker puede contratar abogados especializados en propiedad intelectual para iniciar acciones legales en otros países.

Referencias Legales:
Convenio de Berna para la Protección de las Obras Literarias y Artísticas: Asegura que los derechos de autor de las obras se respeten en los países signatarios.
WIPO: Ofrece mecanismos de resolución de disputas y apoyo en la protección de derechos de propiedad intelectual a nivel internacional.

**Comment by gusta37** [comment]
Ya se paso el wiki
