### ISSUE TITLE
Amparo legal ante adulteración externa de la BSD a nivel nacional e internacional

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#16]
· Si la base de datos es adulterada de manera externa, a nivel nacional, describir qué instrumento legal respalda a ARGBroker.
· Si los datos de la base de datos son adulterados de manera externa, a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

**Comment by AlandMarini** [comment]
**A Nivel Nacional:**
En Argentina, la Ley de Protección de Datos Personales (Ley N° 25.326) respalda a ARGBroker en caso de adulteración de su base de datos. Esta ley establece los principios y regulaciones para el tratamiento de datos personales y proporciona medidas de seguridad y protección de datos. Si se produce una adulteración de la base de datos a nivel nacional, ARGBroker puede invocar esta ley para tomar acciones legales contra los responsables y buscar reparación por cualquier daño causado.

**A Nivel Internacional:**
A nivel internacional, ARGBroker puede invocar acuerdos y convenciones internacionales relacionados con la protección de datos y la seguridad cibernética. El Reglamento General de Protección de Datos (GDPR) de la Unión Europea establece estándares de protección de datos y derechos de privacidad que pueden aplicarse a ciudadanos europeos cuyos datos estén en la base de datos de ARGBroker, incluso si la empresa no está ubicada en la UE. 
Además, tratados internacionales sobre delitos informáticos y ciberseguridad pueden proporcionar bases legales para emprender acciones legales contra los perpetradores de la adulteración de datos a nivel internacional.

**Comment by gusta37** [comment]
Se cargo en el wiki
