### ISSUE TITLE
Negligencia

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#17]
-Cuando los programadores de ARGBroker incurren en una negligencia, a que instrumento legal se acude y quien.

**Comment by AlandMarini** [comment]
El instrumento legal al que se acude es el marco normativo laboral y, específicamente, el contrato de trabajo y la legislación laboral vigente en Argentina. Quienes tienen la responsabilidad de tomar medidas al respecto son los empleadores, representantes legales de ARGBroker, o el departamento de recursos humanos de la empresa.

**Acciones a tomar:**
- Investigación Interna: Se puede iniciar una investigación interna para determinar la naturaleza y la gravedad de la negligencia por parte de los programadores.
- Procedimientos Disciplinarios: Si se determina que ha ocurrido negligencia, la empresa puede aplicar procedimientos disciplinarios, que pueden incluir advertencias, suspensiones o, en casos graves, terminación del contrato laboral.
- Correcciones y Capacitación: Además de tomar medidas disciplinarias, la empresa puede implementar programas de capacitación y mejora continua para prevenir futuras negligencias y mejorar la calidad del trabajo.
- Cumplimiento Legal: Es importante que todas las acciones tomadas estén en conformidad con la legislación laboral vigente y los términos establecidos en los contratos de trabajo.

**Leyes Laborales Federales en Argentina:**
  Ley de Contrato de Trabajo (LCT) (Ley Nº 20.744)
  Ley de Riesgos del Trabajo (LRT) (Ley Nº 24.557)
  Ley Nacional de Empleo (Ley Nº 24.013)

**Leyes Laborales Provinciales en Córdoba:**
  Ley de Empleo Público Provincial (Ley N° 10.430)
  Ley de Contrato de Trabajo para el Personal de la Administración Pública Provincial (Ley Nº 9.579)
  Ley de Riesgos del Trabajo de la Provincia de Córdoba (Ley Nº 9.116)

**Comment by gusta37** [comment]
Ya pasado al wiki
