### ISSUE TITLE
Política de seguridad y respaldo jurídico según la ley de protección de datos.

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#18]
· Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos Personales.
· Si un usuario denuncia a ARGBroker por divulgación de sus datos personales, a que legislación recurrió el mismo y como ARGBroker puede respaldarse jurídicamente.

**Comment by JulioMartin12** [comment]
**Implementación de Seguridad, Ley de Protección de Datos Personales**

Toda empresa que maneja datos personales, tales como los que relaciona a ARGbroker, deba seguir con las siguientes medidas de seguridad según la Ley de Protección de Datos Personales (Ley 25.326 en Argentina) :

**Medidas Técnicas y Organizativas:**

- Implementar controles de acceso por el personal para asegurarse de que sólo los trabajadores autorizados tengan acceso a los datos personales.
- Usar técnicas de cifrado para asegurar los datos, ya sea durante el tráfico y mientras se encuentre almacenado.
- Registrar cualquier acceso o edición de los datos para el acompañamiento de uso no autorizado.

**Confidencialidad e Integridad:**

- Establecer políticas de prevención de divulgación confidencial para el personal encargado de los datos personales.
- Asegurarse de la integridad de los datos mediante técnicas para validarlos.

**Capacitación y Concienciación**

- Se debe capacitar al personal en la importancia de la protección de datos personales y sobre las medidas implementadas.   
- Además, se debe realizar campañas de concientización sobre buenas prácticas en el manejo de datos personales.

**Auditorías y Evaluaciones de Riesgo**

- se deben realizar auditorías y evaluaciones de riesgo de manera periódica. Con esto se puede evaluar el grado de cumplimiento de las medidas de seguridad implementada y descubrir vulnerabilidades.

**Política de Respuesta a Incidentes**

 - Se debe desarrollar y mantener un plan de respuesta a incidentes a fin de mediar posibles violaciones de seguridad.
 -  Informar a la Autoridad de Protección de Datos y los individuos afectados de una brecha de seguridad.

**Respaldo jurídico ante denuncias por divulgación de datos personales**

Un usuario denuncia a ARGBroker por divulgar sus datos personales y solicitar respaldo jurídico. 

**Marco legal**

En Argentina la Ley 25.326 de Protección de Datos Personales. 

**Paso 1 :** Ley  Demostrar el cumplimiento de la Ley 25.326
* Presentar evidencia de políticas y procedimientos de protección de datos implementados; 

 **Paso 2:** Consentimiento :

* Probar la existencia de consentimiento informado del usuario al dar permiso para que los datos sean tratados 
* Mantener registros de consentimiento para el tratamiento de datos personales

﻿**Transparencia y Comunicación:**

- Acreditar que se han informado claramente a los usuarios sobre cómo se manejan sus datos personales, mediante políticas de privacidad y términos de uso accesibles y comprensibles.

**Gestión de Incidentes:**

- Mostrar que se ha actuado conforme al plan de respuesta a incidentes en caso de una brecha de seguridad.
- Documentar todas las acciones tomadas para mitigar el impacto de cualquier incidente de seguridad.

**Colaboración con la Autoridad de Protección de Datos:**

- Colaborar de manera proactiva con la Autoridad de Protección de Datos (APD) en cualquier investigación.
- Presentar toda la documentación requerida por la APD para demostrar el cumplimiento de la normativa.

En resumen, ARGBroker debe garantizar la implementación de medidas de seguridad y mantener una documentación detallada de todas las acciones y políticas relacionadas con la protección de datos personales para respaldarse jurídicamente en caso de una denuncia.
