### ISSUE TITLE
Procedimiento etico

### ISSUE THREAD

**Issue by LucasJQ13** [MassiveCashGuys/proyecto-final-tsds-ispc#19]
· Si el cliente decide reemplazar a ARGBroker por otro proveedor, describir cómo se debe actuar de manera ética ante el cliente y los colegas.

**Comment by AlandMarini** [comment]
Desde el punto de vista de la empresa, es esencial abordar el reemplazo por otro proveedor con profesionalismo y ética en todas las interacciones.

Ante el Cliente, la comunicación debe ser clara y transparente, explicando los motivos del cambio y ofreciendo asistencia durante la transición para garantizar una experiencia sin problemas. Es crucial mostrar respeto por la decisión del cliente y reafirmar el compromiso de la empresa con su satisfacción.

Internamente, se debe coordinar con los equipos relevantes para garantizar una transición ordenada. Brindar apoyo al nuevo proveedor facilita su integración y promueve una cultura de colaboración entre los empleados durante todo el proceso.

Después del cambio, es importante realizar una evaluación interna para identificar áreas de mejora y utilizar la experiencia para fortalecer los procesos internos y mejorar las relaciones con los clientes en el futuro.

**Comment by gusta37** [comment]
ya subido al wiki
