### ISSUE TITLE
#2 Nombrar las clases, atributos y métodos

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#2]
Basándose en los requerimientos funcionales del proyecto ARGBroker Demo, se solicita:

 - Nombrar las clases, atributos y métodos en base a la nomenclatura acordada con el
equipo.

**Comment by marceloportillodev** [comment]
Nomenclaturas

Clases y entidades -> Upper Camel Case. Ej TomCatServer, RestController

Metodos -> Lower Camel Case. Ej firstName, indexNumber

Atributos -> minúscula y en caso de espacios en ER usar _ . Ej codigo_postal, nro_dn

**Comment by gusta37** [comment]
Hecho en el wiki
