### ISSUE TITLE
#3 Identificar las relaciones entre clases.

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#3]
Basándose en los requerimientos funcionales del proyecto ARGBroker Demo, se solicita:

- Identificar las relaciones entre clases.

**Comment by Jmv315** [comment]
La tabla TipoDocumento tiene una relacion 1 a 1 con la tabla Inversor
La tabla Inversor tiene una relacion 1 a 1 con la tabla User
la tabla User tiene una relacion 1 a 1 con la tabla Perfil
La tabla Perfil tiene una relacion 1 a 1 con la tabla Permiso
La tabla Inversor tiene una relacion 1 a 1 con la tabla Portafolio
La tabla Portafolio tiene una relacion 1 a M con la tabla DetallePortafolio
la tabla Inversor tiene una relacion 1 a 1 con la tabla Transaccion
la tabla Transaccion tiene una relacion 1 a 1 con la tabla Accion
