### ISSUE TITLE
#4 Realizar el diagrama de clases

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#4]
Basándose en los requerimientos funcionales del proyecto ARGBroker Demo, se solicita:

- Realizar el diagrama de clases mediante herramientas como draw.io, lucidchart,
creately, miro u otro.

**Comment by marceloportillodev** [comment]
![ProyectoFinal-clases](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/1327770/a3db9b1f-cb80-47af-a866-2760449813df)

**Comment by JulioMartin12** [comment]
**Diagrama Final de la Base de Datos**
![finalBD](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/598c5a40-b234-44d5-8632-f6dc282e7368)

**Comment by JulioMartin12** [comment]
**Diagrama clases**
![diagrama de clases Broker](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/c6aa59e0-85c6-4604-b277-4cfc97e7469f)
![diagrama de clases Broker](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/c6aa59e0-85c6-4604-b277-4cfc97e7469f)
![diagrama de clases Broker](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/c6aa59e0-85c6-4604-b277-4cfc97e7469f)
![diagrama de clases Broker](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/c6aa59e0-85c6-4604-b277-4cfc97e7469f)
![diagrama de clases Broker](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/c6aa59e0-85c6-4604-b277-4cfc97e7469f)

**Comment by gusta37** [comment]
cual dejamos en el wiki?

**Comment by JulioMartin12** [comment]
Diagrama Final con correcciones

![Image](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/ea58a82f-3b1b-4743-9d23-f609e074924c)

**Comment by JulioMartin12** [comment]
con zoom


![Image](https://github.com/MassiveCashGuys/proyecto-final-tsds-ispc/assets/95646667/ad3bcd64-9e4c-4ad7-a7b5-5d71f6f44af3)
