### ISSUE TITLE
#5 Documentar Titulo, Descripción, nomenclatura y comentarios

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#5]
Basándose en los requerimientos funcionales del proyecto ARGBroker Demo, se solicita:

- Documentar el diseño especificando:
      a. Un título significativo. Debe reflejar el propósito del sistema.
      b. Una breve descripción que explique el contexto, objetivo y alcance del
          diagrama.
      c. Nomenclatura elegida para nombres de clases, atributos y métodos.
      d. Comentarios y/o notas que se considere necesario para proporcionar
         información adicional o explicar decisiones de diseño.

**Comment by JulioMartin12** [comment]
a. Un título significativo. Debe reflejar el propósito del sistema.
ARGBroker que representa un sistema de inversión de nacionalidad Argentina

**Comment by JulioMartin12** [comment]
b. Una breve descripción que explique el contexto, objetivo y alcance del
diagrama.

**Contexto**
En el ámbito de las inversiones y el comercio de acciones, **ARGBroker** es un intermediario financiero que facilita la compra y venta de acciones, entre inversores y el mercado.  **ARGBroker** puede ofrecer un servicio de ejecución de órdenes de compra y venta y la gestión del portafolio del cliente.

**Comment by JulioMartin12** [comment]
c. Nomenclatura elegida para nombres de clases, atributos y métodos.
La nomenclatura utilizada:
Para el desarrollo del diagrama de clases utilizaremos la nomenclatura camelCase ya sea para los atributos, metodos y nombre de las clases.
Para el desarrollo del diagrama de la base de dato utilizaremos la nomenclatura snakeCase ya sea para el nombre de las tablas como para el nombre de los atributos de la tabla.

**Comment by JulioMartin12** [comment]
d. Comentarios y/o notas que se considere necesario para proporcionar
información adicional o explicar decisiones de diseño.

El diseño planteado para la base de dato fue consensuado entre los integrantes de la empresa, verificando cada uno de los atributos como también el nombre de las tablas, las cuales sean representativas cuando uno observa el diagrama de la base de datos en su totalidad y facilite una rápida comprensión de los datos que se almacenan en la base de datos y como se relacionan las tablas entre sí.

Realizamos un trabajo del diseño del diagrama de clases teniendo en cuenta el diagrama de la base de datos, teniendo en cuenta los criterios del nombre de los atributos y de las tablas confeccionamos el diagrama de clases, con un trabajo en conjunto de los integrantes.
