### ISSUE TITLE
#1 Identificar las entidades principales del sistema

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#6]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Identificar las entidades principales del sistema.

**Comment by JulioMartin12** [comment]
se agregan a las clases principales las siguientes
User - Son las credenciales para ingresar al sistema
Perfil - Son los tipos de usuarios que tiene el sistema
Permiso - Son los permisos que tiene cada usuario y a que sección del sistema tiene permitido acceder.
Tipo_Documento - Representan los tipos de documentos que existen en el sistema.
Tipo_Inversor - Representan los tipos de inversores que se identifican en el sistema.
Empresa - Son las empresas que hay en el sistema
