### ISSUE TITLE
#2 Definir los atributos para cada entidad

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#7]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Definir los atributos para cada entidad, considerando los datos necesarios para
cumplir con las funcionalidades especificadas.

**Comment by LucasJQ13** [comment]
Atributos de las entidades
1.	Inversor:
A.	DNI (PK)
B.	Nombre
C.	Apellido
D.	Email
E.	Contraseña
F.	Saldo_inicial
2.	Acciones:
A.	ID_empresa
B.	ID_Acción (PK)
C.	Nombre_empresa
D.	Símbolo 
E.	Último_Operado
F.	Cantidad_Compra_diaria
G.	Precio_Compra_actual
H.	Precio_Venta_actual
I.	Cantidad_Venta_diaria
J.	Apertura
K.	Mínimo_diario
L.	Máximo_diario
M.	Último_Cierre
3.	Portafolios:
A.	ID (PK)
B.	ID_Usuario (FK)
C.	Total_invertido
D.	Saldo_cuenta
E.	Ganancia_Pérdida_total
4.	Detalle Portafolio:
A.	ID (PK)
B.	ID_Portafolio (FK)
C.	ID_Acción (FK)
D.	Cantidad_comprada
E.	Monto_invertido
F.	Ganancia_accion
G.	Perdida_accion
5.	Transacciones:
A.	ID (PK)
B.	ID_Usuario (FK)
C.	ID_Acción (FK)
D.	Tipo transacción 
E.	Cantidad
F.	Precio
G.	Fecha_hora
H.	Comisión

**Comment by marceloportillodev** [comment]
En Portafolio, el atributo ganancia y perdida deberían ser dos atributos diferentes

**Comment by JulioMartin12** [comment]
Se agregarían la entidad tipo de documento
TipoDocumento
- id_Tipo_Documento(PK)
- nombre

Se modificaría Inversor
Inversor:
id_Tipo_Documento (PK)(FK)
numero_Documento (PK)
nombre
apellido
email
contraseña
saldo_inicial

**Comment by LucasJQ13** [comment]
agrego a la entidad "empresas" los atributor "pais" e "ingresos_anuales"
