### ISSUE TITLE
#3 Establecer las relaciones entre las entidades identificadas

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#8]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Establecer las relaciones entre las entidades identificadas.

**Comment by Jmv315** [comment]
La tabla TipoDocumento tiene una relacion 1 a 1 con la tabla Inversor
La tabla Inversor tiene una relacion 1 a 1 con la tabla User
la tabla User tiene una relacion 1 a 1 con la tabla Perfil
La tabla Perfil tiene una relacion 1 a 1 con la tabla Permiso
La tabla Inversor tiene una relacion 1 a 1 con la tabla Portafolio
La tabla Portafolio tiene una relacion 1 a M con la tabla DetallePortafolio
la tabla Inversor tiene una relacion 1 a 1 con la tabla Transaccion
la tabla Transaccion tiene una relacion 1 a 1 con la tabla Accion
La tabla TipoTransaccion tiene una relacion 1 a 1 con la tabla Transaccion
La tabla Empresa tiene una relacion M a 1 con la tabla Acciones
La tabla TipoInversor tiene una relacion 1 a 1 con la tabla Inversor

**Comment by LucasJQ13** [comment]
Modifico y agrego algunas aclaraciones.

La tabla TipoDocumento tiene una relacion 1 a 1 con la tabla Inversor: Se asumió una relación 1:1 ya que cada inversor debe tener un único tipo de documento.
La tabla Perfil tiene una relacion 1 a 1 con la tabla User: Se asumió una relación 1:1 ya que cada inversor debe estar asociado a un único usuario y cada usuario a un único inversor.
la tabla User tiene una relación 1 a 1 con la tabla Perfil: Se asumió una relación 1:1 ya que cada usuario debe tener un único perfil.
La tabla Perfil tiene una relación 1 a 1 con la tabla Permiso: Se asumió una relación 1:1 ya que cada perfil debe tener un único permiso.
La tabla Inversor tiene una relación 1 a 1 con la tabla Portafolio: Se asumió una relación 1:1 ya que cada inversor debe tener un único portafolio.
La tabla Portafolio tiene una relación 0 a * con la tabla DetallePortafolio: Cada Portafolio puede tener múltiples DetallePortafolio (o ninguno), pero cada DetallePortafolio está asociado a un único Portafolio.
la tabla Inversor tiene una relación 1 a * con la tabla Transacción: Cada Inversor puede tener múltiples Transacción, pero cada Transacción está asociada a un único Inversor.
la tabla Transacción tiene una relación 1 a 1 con la tabla Acción: Se asumió una relación 1:1 ya que cada transacción debe estar asociada a una única acción.
La tabla Transacción tiene una relación 1 a 1 con la tabla TipoTransaccion: Se asumió una relación 1:1 ya que cada transacción debe tener un único tipo de transacción.
La tabla Empresa tiene una relación 1 a 1 con la tabla Acciones: Se asumió una relación 1:1 ya que cada acción está asociada a una única empresa.
La tabla TipoInversor tiene una relación 1 a 1 con la tabla Inversor: Cada Inversor está asociado a un único TipoInversor y cada TipoInversor está asociado a un único Inversor.
