### ISSUE TITLE
#4 Aplicar el proceso de normalización a las entidades y sus atributos

### ISSUE THREAD

**Issue by marceloportillodev** [MassiveCashGuys/proyecto-final-tsds-ispc#9]
Basándose en los requerimientos funcionales del proyecto, se solicita realizar el diseño de
la base de datos para la aplicación ARGBroker Demo.

- Aplicar el proceso de normalización a las entidades y sus atributos para eliminar
  redundancias y dependencias funcionales. Se debe alcanzar la Tercera Forma
  Normal (3FN).

**Comment by LucasJQ13** [comment]
Aplicamos el proceso de normalización de nuestra base de datos.

Primera forma normal (1FN): En este proceso identificamos las principales entidades del sistema y establecimos las claves primarias y nos aseguramos de que no existan valores repetidos ni redundantes.

Entidades identificadas:

1. Inversor
2. Portafolio
3. Detalle Portafolio
4. Transacciones

Segunda forma normal (2FN): En esta parte del proceso nos aseguramos que los atributos no clave sean dependientes de las claves primarias y separamos las en otras entidades.

1. Inversor
2. Acción
3. Transacción
4. Portafolio
5. Detalle Portafolio
6. Empresa

Tercera forma normal (3FN):  En el ultimo proceso de normalización de la base de datos nos aseguramos de que todos los atributos no clave dependen de la clave primaria o de otros atributos clave y que no dependan de un atributo a través de otro, esto eliminando dependencias transitivas. Las entidades finales son las siguientes.

1. Inversor
2. Tipo de Inversor
3. User
4. Perfil
5. Portafolio
6. Detalle Portafolio
7. Tipo de Documento
8. Permiso
9. Transaccion
10. Accion
11. Tipo de Transaccion
12. Empresa
